### PR TITLE
Store extendedBlockRenderMap in state so it can be updated when readOnly changes its value

### LINKED ISSUE #324: Update movable blocks if readOnly props changes
# -- Bug Report --

## Expected Behavior
When I change the prop readOnly, Megadraft should remove the possibility of moving blocks even if it's already instantiated.

## Current Behavior
Changing the prop readOnly to true makes the text uneditable but the move blocks wrapper is still present.

## Steps to Reproduce
1. Create an instance of Megadraft with `readOnly` prop equals `false`
2. In the same instance of Megadraft, change `readOnly` to `true`
3. You cant't edit the text but the move blocks wrapper is still present over every block
4. The same happens with opposite steps. Changing `readOnly` to `false` the movable blocks wrapper does not return

### PR DESCRIPTION
**Pull request by lousander**
Fixes #324

### CODE REVIEW

**Review by richardkevin — APPROVED** [review]

File: src/components/MegadraftEditor.js [hunk 1]
```diff
@@ -57,13 +57,15 @@ export default class MegadraftEditor extends Component {
 
   constructor(props) {
     super(props);
+    const readOnly = this.props.readOnly || false;
```
Comment (igor-giusti) [inline src/components/MegadraftEditor.js:60]: Why not `defaultProps`?

**Review by igor-giusti — APPROVED** [review]
